**NumPy** - numerical python

                     Advantages of numpy : allow faster and several operation

In [1]:
#importing library
import numpy as np

**Array Creation**

1D array - similar to vectors

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a.shape

(5,)

2D array - similar to matrices

In [4]:
b = np.array([[2,4,6,8],[1,3,5,7]])
print(b)

[[2 4 6 8]
 [1 3 5 7]]


In [5]:
b.shape

(2, 4)

dtype - tells about the data type of array

In [7]:
c = np.array([[2,4,6,8],[1,3,5,7]], dtype = float)
print(c)

[[2. 4. 6. 8.]
 [1. 3. 5. 7.]]


**Initial Placeholders**

Zeros

In [8]:
zero = np.zeros((3,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Ones

In [9]:
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


Particular Value

In [13]:
x = np.full((2,3),5)
print(x)

[[5 5 5]
 [5 5 5]]


Identity

In [12]:
id = np.eye(4,4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random numbers (0 to 1)

In [14]:
rd = np.random.random((2,3))
print(rd)

[[0.76860726 0.25753912 0.51248977]
 [0.65908405 0.46026469 0.10694456]]


Random Integer Numbers

In [15]:
random_int = np.random.randint(1, 10, (3,3))
print(random_int)

[[3 6 4]
 [1 5 8]
 [4 3 2]]


In [16]:
random_int = np.random.randint(10, 100, (3,5))
print(random_int)

[[52 92 30 20 95]
 [36 57 56 84 95]
 [45 39 74 95 69]]


Evenly Spaced Values

In [21]:
ls = np.linspace(5, 15, 3)
print(ls)

[ 5. 10. 15.]


Evenly spaced with Step

In [23]:
ar = np.arange(10,50,6)
print(ar)

[10 16 22 28 34 40 46]


**List to an Array**

In [24]:
li = [1,2,3,4,5,6]
ar = np.asarray(li)
print(ar)

[1 2 3 4 5 6]


**Analyzing a numpy array**

In [25]:
a = np.random.randint(10, 90, (5,5))
print(a)

[[37 38 10 50 34]
 [48 89 89 45 41]
 [81 89 55 84 22]
 [87 44 32 75 18]
 [56 37 10 25 73]]


shape - tell rows and columns

In [26]:
a.shape

(5, 5)

ndim - no. of dimensions

In [27]:
a.ndim

2

size - no.of elements in an array

In [29]:
a.size

25

dtype - tells datatype

In [30]:
a.dtype

dtype('int64')

**Mathematical Operations on an aray**

Creating two arrays

In [32]:
a = np.random.randint(0,10,(3,3))
print(a)

[[9 9 7]
 [6 4 3]
 [3 4 7]]


In [33]:
b = np.random.randint(10,20,(3,3))
print(b)

[[16 10 16]
 [15 18 13]
 [13 11 14]]


Addition

In [34]:
np.add(a,b)

array([[25, 19, 23],
       [21, 22, 16],
       [16, 15, 21]])

Subtraction

In [35]:
np.subtract(a,b)

array([[ -7,  -1,  -9],
       [ -9, -14, -10],
       [-10,  -7,  -7]])

Multiply

In [36]:
np.multiply(a,b)

array([[144,  90, 112],
       [ 90,  72,  39],
       [ 39,  44,  98]])

Divide

In [38]:
np.divide(a,b)

array([[0.5625    , 0.9       , 0.4375    ],
       [0.4       , 0.22222222, 0.23076923],
       [0.23076923, 0.36363636, 0.5       ]])

**Statitical operations**

Creating an array

In [39]:
s = np.random.randint(10,20,(4,4))
print(s)

[[19 14 15 13]
 [11 18 15 15]
 [12 15 17 15]
 [10 16 14 19]]


Mean

In [42]:
np.mean(s)

np.float64(14.875)

Median

In [44]:
np.median(s)

np.float64(15.0)

Mode

In [47]:
from scipy import stats

s = stats.mode(s, keepdims= True)
print(s.mode[0])

[1 1 1 1]


Range

In [49]:
r = np.max(s) - np.min(s)
print(r)

1


Variance

In [50]:
np.var(s)

np.float64(0.1875)

Standard deviation

In [51]:
np.std(s)

np.float64(0.4330127018922193)

**Set Operations**

In [52]:
x = np.random.randint(1,10,(3,3))
print(x)

[[6 4 4]
 [7 3 4]
 [7 3 1]]


In [53]:
y = np.random.randint(1,10,(3,3))
print(y)

[[5 3 2]
 [3 1 3]
 [2 9 5]]


Union

In [54]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 9])

Intersection

In [55]:
np.intersect1d(x,y)

array([1, 3])

Set Difference

In [56]:
np.setdiff1d(x,y)

array([4, 6, 7])

**Array Manipulation**

array creation

In [57]:
a = np.random.randint(1,10,(3,3))
print(a)

[[9 7 6]
 [5 6 7]
 [1 6 1]]


Transpose

In [59]:
a.T

array([[9, 5, 1],
       [7, 6, 6],
       [6, 7, 1]])

Reshape

In [61]:
a.reshape(3,3)

array([[9, 7, 6],
       [5, 6, 7],
       [1, 6, 1]])

flatten

In [62]:
a.flatten()

array([9, 7, 6, 5, 6, 7, 1, 6, 1])

Ravel

In [63]:
a.ravel()

array([9, 7, 6, 5, 6, 7, 1, 6, 1])

**Linear Algebra**

In [65]:
a = np.random.randint(1,10,(3,3))
print(a)

[[3 5 9]
 [5 8 6]
 [2 2 3]]


In [66]:
b = np.random.randint(1,10,(3,3))
print(b)

[[7 7 3]
 [9 7 8]
 [9 1 4]]


Dot Product

In [67]:
np.dot(a,b)

array([[147,  65,  85],
       [161,  97, 103],
       [ 59,  31,  34]])

Determinant

In [68]:
np.linalg.det(a)

np.float64(-32.999999999999986)

Inverse

In [69]:
np.linalg.inv(a)

array([[-0.36363636, -0.09090909,  1.27272727],
       [ 0.09090909,  0.27272727, -0.81818182],
       [ 0.18181818, -0.12121212,  0.03030303]])

Eigen Value

In [70]:
np.linalg.eig(a)

EigResult(eigenvalues=array([13.67736889, -1.4003398 ,  1.72297092]), eigenvectors=array([[-0.57719648, -0.91066066,  0.54255033],
       [-0.77625569,  0.31017368, -0.76463403],
       [-0.25351792,  0.27292755,  0.34781307]]))

**Indexing**

In [73]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [74]:
arr[0]

np.int64(1)

In [75]:
arr[4]

np.int64(5)

In [76]:
arr[-1]

np.int64(6)

**Slicing** - extracting subset of data

In [79]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [84]:
a[0:2]  #2-1 = 1

array([1, 2])

In [85]:
a[2:len(a)]

array([3, 4, 5])

In [86]:
a[0::2]  #step

array([1, 3, 5])

**Fancy Indexing** - selecting multiple indexes

In [87]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [90]:
print(a[1:2:4])

[2]


**Filtering** - bolean masking

In [91]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [92]:
arr[arr>4]

array([5, 6])

**Insering an element**

1D array

In [93]:
x = np.array([2,4,6,8,10])
print(x)

[ 2  4  6  8 10]


In [96]:
np.insert(x, 2, 5, axis = 0)  #(arr name, index, value, axis = 0)

array([ 2,  4,  5,  6,  8, 10])

2D array

In [97]:
y = np.array([[1,2,3,4],[9,10,11,12]])
print(y)

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [98]:
np.insert(y,1, [5,6,7,8], axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Delete an element**

In [99]:
d = np.array([22,14,6,18,10])
print(d)

[22 14  6 18 10]


In [101]:
np.delete(d, 2)  #(arr name, index)

array([22, 14, 18, 10])

**Append an element**

In [102]:
app = np.array([22,14,6,18,10])
print(app)

[22 14  6 18 10]


In [103]:
np.append(app, 5)  #(arr name, value)

array([22, 14,  6, 18, 10,  5])

**Concatenate an array**

In [104]:
a1 = np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [105]:
a2 = np.array([5,6,7,8])
print(a2)

[5 6 7 8]


In [106]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

**Stacking**

In [108]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [111]:
np.vstack((a1,a2))  #row-wise stacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
np.hstack((a1,a2))  #column-wise stacking

array([1, 2, 3, 4, 5, 6, 7, 8])

**Broadcasting**

In [119]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


Matching Dimensions

In [120]:
c = np.array([1,2,3,4])

In [121]:
np.add(a,c)

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

Expanding single array

In [125]:
print(a)
b = 3
a * b

[[1 2 3 4]
 [5 6 7 8]]


array([[ 3,  6,  9, 12],
       [15, 18, 21, 24]])

Incompatible Shapes - error

**Handle Missing Values**

 **nan()** - checking for missing values

In [127]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(arr)

[ 1.  2.  3. nan  5.  6.  7. nan]


**nan_to_num()** -  replace nan values

In [128]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
n_arr = np.nan_to_num(arr)
print(n_arr)

[1. 2. 3. 0. 5. 6. 7. 0.]


**isinf()** - checks for infinity values

In [129]:
arr = np.array([1,2,np.inf, 3])
print(arr)

[ 1.  2. inf  3.]
